version: 0.0
os: linux
files:
  - source: scripts/start_container.sh
    destination: /opt/codedeploy-agent/deployment-root/scripts/
  - source: scripts/stop_container.sh
    destination: /opt/codedeploy-agent/deployment-root/scripts/
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
    
